version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rsvshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qhraksgdl07
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rsvshop-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - "4900:4900"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - /app/prisma/dev.db
    environment:
      - NODE_ENV=development
      - PORT=4900
      - HOSTNAME=0.0.0.0
      - DATABASE_URL=postgresql://postgres:qhraksgdl07@postgres:5432/rsvshop
      - TZ=Asia/Seoul
      - NODE_OPTIONS=--max-old-space-size=2048
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm install && npx prisma generate && npx prisma db push && npx next dev -p 4900 -H 0.0.0.0 --turbo"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4900/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data: 